spring:
  application:
    name: jdbc
management:
  context_path: /admin
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    # org.springframework.security: DEBUG

server:
  port: 8080